# although Lmod is written in Lua, use Python environment
language: python
sudo: false

env:
  - LUA='lua=5.1'
  - LUA='lua=5.2'
  - LUA='lua=5.3'

addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - tcsh
      - tcl8.5
      - uuid  # for uuidgen

before_install:
  - cd $HOME
  # install Lua via hererocks
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH="$PWD/lua_install/bin:$PATH"
  # install Hermes test tool
  - git clone https://github.com/TACC/Hermes.git
  - export PATH="$PWD/Hermes/bin:$PATH"
  # install CMake (explicitly use 3.6 since it's the minimum required)
  - curl https://cmake.org/files/v3.6/cmake-3.6.0-Linux-x86_64.tar.gz | tar -xz
  - export PATH="$PWD/cmake-3.6.0-Linux-x86_64/bin:$PATH"
  - cd -
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update -q
  - sudo install r-base r-base-dev


install:
  - luarocks install luaposix
  - luarocks install luafileSystem
  - luarocks install luajson
  - luarocks install lua-term

script:
  # run Lmod test suite with Hermes
  - tm

after_failure:
  # diff stdout/stderr for all tests in case of failure
  - for dir in $(ls -pd rt/* | grep '/$'); do
    echo ">>>> ${dir}/err.txt"; diff -u ${dir}/t1/*/_err.left ${dir}/t1/*/_err.right;
    echo ">>>> ${dir}/out.txt"; diff -u ${dir}/out.txt        ${dir}/t1/*/out.txt;
    done
